[package]

name = "transporter"
version = "0.7.0"
authors = ["Roey Darwish Dror <roeyd@infinidat.com>"]

[dependencies]
byteorder = "*"
docopt = "*"
fern = "*"
log = "*"
rustc-serialize = "*"
url = "*"
hyper = "*"
time = "*"
rust-crypto = "*"

[dependencies.raven]
git = "https://github.com/r-darwish/raven-rust.git"
