[package]

name = "transporter"
version = "0.1.0"
authors = ["Roey Darwish Dror <roeyd@infinidat.com>"]

[dependencies]
byteorder = "*"
docopt = "*"
env_logger = "*"
log = "*"
rustc-serialize = "*"
url = "*"
hyper = "*"
