[package]

name = "transporter"
version = "0.2.0"
authors = ["Roey Darwish Dror <roeyd@infinidat.com>"]

[dependencies]
byteorder = "*"
docopt = "*"
env_logger = "*"
log = "*"
rustc-serialize = "*"
url = "*"
hyper = "*"

[dependencies.raven]
git = "https://github.com/r-darwish/raven-rust.git"
