- name: fetch Rust 1.6.0
  shell: curl https://static.rust-lang.org/dist/rust-1.6.0-x86_64-unknown-linux-gnu.tar.gz | tar xz
  args:
    chdir: /tmp
    creates: /tmp/rust-1.6.0-x86_64-unknown-linux-gnu

- name: install Rust
  shell: ./install.sh
  args:
    chdir: /tmp/rust-1.6.0-x86_64-unknown-linux-gnu
