- name: fetch Rust nightly
  shell: wget https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  args:
    chdir: /tmp
    creates: /tmp/rust-nightly-x86_64-unknown-linux-gnu.tar.gz

- name: extract Rust
  unarchive: src=/tmp/rust-nightly-x86_64-unknown-linux-gnu.tar.gz dest=/tmp copy=no

- name: install Rust
  shell: ./install.sh
  args:
    chdir: /tmp/rust-nightly-x86_64-unknown-linux-gnu

- name: remove rust installation dir and archive
  file: path=/tmp/{{ item }} state=absent
  with_items:
    - rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    - rust-nightly-x86_64-unknown-linux-gnu
